server {
    listen 8080;
    gzip on;
    gzip_types text/plain text/css application/json application/javascript;
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}
