app = "demo-app-web-prod"
primary_region = "sin"

[build]
  dockerfile = "frontend/Dockerfile"

  [build.args]
    MODE = "production"
    VITE_API_URL = "https://demo-app-api-prod.fly.dev"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = "256mb"
  cpu_kind = "shared"
  cpus = 1
